aaa: Shellcheck fixes

diff --git a/scripts/aaa b/scripts/aaa
--- a/scripts/aaa
+++ b/scripts/aaa
@@ -3,21 +3,21 @@
 # aaa: auto albumart
 
 function installed() {
-	local cmd=$(command -v "${1}")
+	cmd=$(command -v "${1}")
 
 	[[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
 	return ${?}
 }
 
-installed albumart || { printf "Missing albumart.\n" ; exit ; }
+installed albumart || { echo "Missing albumart." ; exit ; }
 
 artist=$(basename "${PWD}")
 albums=($(find . -maxdepth 1 -mindepth 1 -type d -printf '%f\n'))
 
 [[ -z "${albums[*]}" ]] && { printf "No albums found.\n" ; exit ; }
 
-printf "Artist: ${artist}\n"
-printf "Albums: ${albums[*]}\n"
+echo "Artist: ${artist}"
+echo "Albums: ${albums[*]}"
 
 read -e -p "Continue? (y/N) " prompt
 
@@ -26,9 +26,9 @@ read -e -p "Continue? (y/N) " prompt
 pushd . > /dev/null
 
 for album in "${albums[@]}"; do
-	cd "${album}"
+	pushd "${album}" > /dev/null
 	albumart "${artist} - ${album}" 2> /dev/null
-	cd ..
+	popd > /dev/null
 done
 
 popd > /dev/null
