scripts: Update kbs2-qr

diff --git a/scripts/kbs2-qr b/scripts/kbs2-qr
--- a/scripts/kbs2-qr
+++ b/scripts/kbs2-qr
@@ -12,8 +12,14 @@ function installed() {
 }
 
 installed qrencode || { >&2 echo "Missing dependency: qrencode."; exit 1; }
-installed feh || { >&2 echo "Missing dependency: feh."; exit 1; }
+
+if [[ $(uname -s) == "Darwin" ]]; then
+  display="open -a Preview.app -f"
+else
+  installed feh || { >&2 echo "Missing dependency: feh."; exit 1; }
+  display="feh -"
+fi
 
 [[ -n "${1}" ]] || { echo "Usage: kbs2 qr <login>"; exit; }
 
-kbs2 pass "${1}" | qrencode -s 12 -o - | feh -
+kbs2 pass "${1}" | qrencode -s 12 -o - | ${display}
