nautilus-xenial-gopro-install: update

diff --git a/scripts/nautilus-xenial-gopro-install b/scripts/nautilus-xenial-gopro-install
--- a/scripts/nautilus-xenial-gopro-install
+++ b/scripts/nautilus-xenial-gopro-install
@@ -1,28 +1,13 @@
 #!/usr/bin/env bash
 # -------------------------------------------------------------
-# Installation of updated gphoto libraries to avoid corrupted DCIM with latest GoPro
+# Handle installation, update or removal of updated
+# gphoto libraries to avoid corrupted DCIM with latest GoPro
 #
 # Revision history :
-#   25/09/2016, V1.0 - Creation by N. Bernaerts
+#   20/06/2016, V1.0 - Creation by N. Bernaerts
+#   20/07/2017, V2.0 - Complete rework to become update proof
+#   16/02/2018, V2.1 - Change to lauchpad Ubuntu repository
 # -------------------------------------------------------------
-
-# -------------------------------------------------------
-#   Loop to load arguments
-# -------------------------------------------------------
-
-if [ ! -f /etc/os-release ]
-then
-  echo "Missing /etc/os-release, couldn't detect distro/version."
-  exit
-else
-  source /etc/os-release
-  if [ "${VERSION_ID}" != "16.04" ]
-  then
-    echo "You're not running Ubuntu 16.04."
-    echo "This script might work, but probably not."
-    exit
-  fi
-fi
 
 # if no argument, display help
 if [ $# -eq 0 ]
@@ -31,6 +16,7 @@ then
   echo "Parameters are :"
   echo "  --install       Install and declare the updated library"
   echo "  --remove        Back to original library"
+  echo "  --update        Re-declare updated libraries"
   exit
 fi
 
@@ -40,68 +26,117 @@ do
   case "$1" in
     "--install") MODE="install"; shift; ;;
     "--remove") MODE="remove"; shift; ;;
+    "--update") MODE="update"; shift; ;;
     *) shift; ;;
-   esac
+  esac
 done
 
-# check --install or --remove mode
-[ "${MODE}" != "install" -a "${MODE}" != "remove" ] && { echo "Please use --install or --remove"; exit 1; }
+# check --update or --cleanup mode
+[ "${MODE}" = "" ] && { echo "Please use --install, --remove or --update mode"; exit 1; }
 
-# ---------------------------------------------------
-#  Cleaning
-# ---------------------------------------------------
+# generate temporary file
+TMP_DEB=$(mktemp -t "XXXXXXXX.deb")
 
-# remove targeted files and directories
-sudo rm -f /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
-sudo rm -R /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
-sudo rm -f /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
-sudo rm -R /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
-sudo rm -f /lib/udev/hwdb.d/20-libgphoto2-6.hwdb
+# select mode
+case "${MODE}" in
 
-# ---------------------------------------------------
-#  Installation mode
-# ---------------------------------------------------
+  # ---------------------------
+  #   Installation mode
+  # ---------------------------
+  "install")
 
-if [ "${MODE}" = "install" ]
-then
-  # create /opt/libgphoto2 directory structure
-  sudo mkdir --parent /opt/libgphoto2
+    # create main directory
+    mkdir --parent /opt/libgphoto2
 
-  # unpack and declare libgphoto2-port12
-  wget http://fr.archive.ubuntu.com/ubuntu/pool/main/libg/libgphoto2/libgphoto2-port12_2.5.10-3_amd64.deb
-  dpkg --fsys-tarfile libgphoto2-port12_2.5.10-3_amd64.deb | sudo tar xf - -C /opt/libgphoto2
-  sudo ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
-  sudo ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
+    # libgphoto2-port12 : unpack
+    echo "Install libgphoto2-port12"
+    wget --quiet -O ${TMP_DEB} "https://launchpad.net/ubuntu/+archive/primary/+files/libgphoto2-port12_2.5.10-3_amd64.deb"
+    dpkg --fsys-tarfile ${TMP_DEB} | tar xf - -C /opt/libgphoto2
 
-  # unpack and declare libgphoto2
-  wget http://fr.archive.ubuntu.com/ubuntu/pool/main/libg/libgphoto2/libgphoto2-6_2.5.10-3_amd64.deb
-  dpkg --fsys-tarfile libgphoto2-6_2.5.10-3_amd64.deb | sudo tar xf - -C /opt/libgphoto2
-  sudo ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2.so.6.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
-  sudo ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10 /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
-  sudo ln -s /opt/libgphoto2/lib/udev/hwdb.d/20-libgphoto2-6.hwdb /lib/udev/hwdb.d/20-libgphoto2-6.hwdb
+    # libgphoto2-port12 : declare
+    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
+    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
+    rm -Rf /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
+    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
 
-  # remove downloaded pacakges
-  rm libgphoto2-port12_2.5.10-3_amd64.deb libgphoto2-6_2.5.10-3_amd64.deb
+    # libgphoto2 : unpack
+    echo "Install libgphoto2-6"
+    wget --quiet -O ${TMP_DEB} "https://launchpad.net/ubuntu/+archive/primary/+files/libgphoto2-6_2.5.10-3_amd64.deb"
+    dpkg --fsys-tarfile ${TMP_DEB} | tar xf - -C /opt/libgphoto2
 
-# ---------------------------------------------------
-#  Removal mode
-# ---------------------------------------------------
+    # libgphoto2 : declare
+    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
+    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2.so.6.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
+    rm -Rf /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
+    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10 /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
+    rm -f /lib/udev/hwdb.d/20-libgphoto2-6.hwdb
+    ln -s /opt/libgphoto2/lib/udev/hwdb.d/20-libgphoto2-6.hwdb /lib/udev/hwdb.d/20-libgphoto2-6.hwdb
 
-elif [ "${MODE}" = "remove" ]
-then
-  # remove /opt/libgphoto2 directory structure
-  sudo rm -R /opt/libgphoto2
+    # download this script (for post install hook)
+    wget --quiet -O /opt/libgphoto2/nautilus-xenial-gopro https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/nautilus-xenial-gopro
+    chmod +x /opt/libgphoto2/nautilus-xenial-gopro
 
-  # reinstall original packages
-  sudo apt-get install --yes --reinstall libgphoto2-6 libgphoto2-port12
-fi
+    # apt post install hook : download and declare
+    echo "Install apt post install hook"
+    wget --quiet -O /etc/apt/apt.conf.d/99nautilus-xenial-gopro https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/99nautilus-xenial-gopro
+    ;;
 
-# ---------------------------------------------------
-#  Restart services
-# ---------------------------------------------------
+  # ---------------------------
+  #   Removal mode
+  # ---------------------------
+  "remove")
+
+    # remove targeted files and directories
+    echo "Remove links"
+    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
+    rm -Rf /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
+    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
+    rm -Rf /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
+    rm -f /lib/udev/hwdb.d/20-libgphoto2-6.hwdb
+
+    # remove apt post install hook
+    rm /etc/apt/apt.conf.d/99nautilus-xenial-gopro
+
+    # reinstall original packages
+    echo "Reinstall original libgphoto packages"
+    apt-get install --yes --reinstall libgphoto2-6 libgphoto2-port12
+
+    # remove /opt/libgphoto2 directory structure
+    rm -Rf /opt/libgphoto2
+    ;;
+
+  # ---------------------------
+  #   Update mode
+  # ---------------------------
+  "update")
+
+    # remove original libgphoto2_port and create links
+    echo "Declare libgphoto2_port12"
+    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
+    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
+    rm -Rf /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
+    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
+
+    # remove original libgphoto2 and create links
+    echo "Declare libgphoto2-6"
+    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
+    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2.so.6.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
+    rm -Rf /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
+    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10 /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
+    rm -f /lib/udev/hwdb.d/20-libgphoto2-6.hwdb
+    ln -s /opt/libgphoto2/lib/udev/hwdb.d/20-libgphoto2-6.hwdb /lib/udev/hwdb.d/20-libgphoto2-6.hwdb
+    ;;
+
+  *)
+    ;;
+
+esac
+
+# cleanup temporary file
+rm -f ${TMP_DEB}
 
 # update hardware database
-sudo udevadm hwdb --update
+udevadm hwdb --update
 
 # restart udev service
-sudo service udev restart
+service udev restart
